export const ADD_CLASS_REQUESTED = 'ADD_CLASS_REQUESTED';
export const ADD_CLASS_SUCCEEDED = 'ADD_CLASS_SUCCEEDED';

export const LIST_CLASS_REQUESTED = 'LIST_CLASS_REQUESTED';
export const LIST_CLASS_SUCCEEDED = 'LIST_CLASS_SUCCEEDED';
